### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by mwarning**
Fixes some compiler warning and apply a unified indentation.

### CODE REVIEW

**Comment by nicopace** [comment]
Hi @mwarning , thanks for this.
Haven't tested it, would love to know what use are you planning for it.
We were thinking on using it for detecting if there is a rogue dhcp in the network.
the method would be: when a cable is connected to a socket in the router, put it aside in a vlan, send a dhcp request... if there is a dhcp, then we need to deal with it separately. if not, we can make it join the general bridge of wireless+wired+batman.

**Comment by mwarning** [comment]
I tried to use it to detect the presence of a dhcp server (but not freifunk/mesh related at all), but I found another solution that works for that specific case.

**Comment by nicopace** [comment]
Can you share your solution?
What about using this? did it worked for you>

**Comment by mwarning** [comment]
I cannot share the code, but it uses odhcpd.

**Comment by nicopace** [comment]
What a pitty that you can't share it.
Still, thanks for sharing your experience!

**Comment by mwarning** [comment]
np, glad I can contribute something back! :)

**Pull request merged**
